name: Continuous Development

# Trigger the CD pipeline only when pushing to the master branch
on:
 
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
   run-after:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:

      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build msi package
      - name: Build MSI Package
        run: dotnet build SystemHealthMonitor/SystemHealthMonitor.MSI/SystemHealthMonitor.MSI.wixproj -c Release -o installer

      # Step 3: Build burn installer
      - name: Build Burn Installer
        run: dotnet build SystemHealthMonitor/SystemHealthMonitor.BundleInstaller/SystemHealthMonitor.BundleInstaller.wixproj -c Release -o installer
      
      # Step 4: Upload Burn installer to release assets
      - name: Move Burn Installer to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SystemHealthMonitor/installer/SystemHealthMonitor.BundleInstaller.exe